from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Tuple
import json
import re

from .file_locks import reserve_targets


@dataclass
class WriteDecision:
    allowed: List[str]
    blocked: List[str]
    reason: str


def allowed_targets_for_tier(tier: str) -> List[str]:
    if tier == 'T5':
        return ['.codex/analysis/', '.codex/runtime/runs/']
    if tier == 'T4':
        return ['.codex/analysis/', '.codex/runtime/runs/', '.codex/contracts/']
    if tier == 'T3':
        return ['.codex/runtime/runs/workspace-mirror/', 'README.md', '.codex/docs/', '.codex/templates/']
    if tier == 'T2':
        return ['.codex/runtime/runs/workspace-mirror/', '.codex/docs/', '.codex/contracts/', '.codex/config/']
    if tier == 'T1':
        return ['.codex/runtime/runs/workspace-mirror/', '.codex/docs/', '.codex/contracts/', '.codex/config/', 'README.md', 'AGENTS.md']
    return ['.codex/runtime/runs/']


def decide_write_targets(root: Path, run_root: Path, tier: str, requested: Iterable[str]) -> WriteDecision:
    allowed_prefixes = allowed_targets_for_tier(tier)
    allowed: List[str] = []
    blocked: List[str] = []
    for raw in requested:
        rel = raw.strip().removeprefix('./')
        if not rel:
            continue
        normalized = rel.replace('\\', '/')
        ok = any(normalized == prefix.rstrip('/') or normalized.startswith(prefix) for prefix in allowed_prefixes)
        if ok:
            allowed.append(normalized)
        else:
            blocked.append(normalized)
    reason = 'scoped tier whitelist enforced'
    return WriteDecision(allowed=allowed, blocked=blocked, reason=reason)


def extract_requested_targets(prompt: str, relevant_files: List[str]) -> List[str]:
    prompt_files = re.findall(r'([A-Za-z0-9_./-]+\.(?:md|py|sh|json|txt))', prompt)
    return list(dict.fromkeys(prompt_files + relevant_files[:4]))


def reserve_write_targets(root: Path, run_root: Path, owner: str, targets: Iterable[str]) -> Tuple[List[str], List[str]]:
    """Reserve repo-global targets before writing into the workspace mirror.

    Even though safe writes land in the run mirror, the reserved key is the real repo
    target so concurrent runs cannot stage competing edits for the same file unnoticed.
    """
    return reserve_targets(root, run_root, owner, targets)


def materialize_safe_writes(root: Path, run_root: Path, tier: str, targets: Iterable[str], owner: str = "unknown") -> List[str]:
    decision = decide_write_targets(root, run_root, tier, targets)
    acquired, blocked_by_lock = reserve_write_targets(root, run_root, owner, decision.allowed)
    decision.blocked.extend(blocked_by_lock)
    decision.allowed = acquired
    written: List[str] = []
    sandbox_root = run_root / 'workspace-mirror'
    for rel in decision.allowed:
        if rel.startswith('.codex/runtime/runs/workspace-mirror/'):
            dest = run_root / rel.removeprefix('.codex/runtime/runs/')
        elif rel in {'README.md', 'AGENTS.md'} or rel.startswith('.codex/'):
            dest = sandbox_root / rel
        else:
            dest = sandbox_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        src = root / rel if (root / rel).exists() else None
        if src and src.is_file():
            original = src.read_text(encoding='utf-8')
            payload = original + f'\n<!-- runtime mirror update by {tier} -->\n'
        else:
            payload = f'# Simulated write\n\nGenerated by tier {tier}.\n'
        dest.write_text(payload, encoding='utf-8')
        written.append(str(dest.relative_to(run_root)))
    policy = {
        'tier': tier,
        'allowed': decision.allowed,
        'blocked': decision.blocked,
        'reason': decision.reason,
    }
    (run_root / 'logs').mkdir(parents=True, exist_ok=True)
    (run_root / 'logs' / f'write-policy-{tier}.json').write_text(json.dumps(policy, indent=2), encoding='utf-8')
    return written
